import { TypePropertyDATA } from "./types";

export const propertyDataFromAPI: TypePropertyDATA = {
  listingProvider: null,
  zpid: 28138536,
  buildingPermits: null,
  propertyTaxRate: 1.6,
  contact_recipients: [
    {
      agent_reason: 1,
      zpro: null,
      recent_sales: 0,
      review_count: 0,
      display_name: "Glenda Abiaka",
      zuid: "X1-ZUy3c6as22cyrt_4ye7o",
      rating_average: 0,
      badge_type: "Premier Agent",
      phone: [Object],
      image_url:
        "https://photos.zillowstatic.com/h_n/ISjb8di8mvv6p01000000000.jpg",
    },
  ],
  zipcode: "77047",
  openHouseSchedule: {},
  longitude: -95.36764,
  zestimateLowPercent: "5",
  address: {
    community: null,
    city: "Houston",
    state: "TX",
    neighborhood: null,
    subdivision: null,
    streetAddress: "12822 Southbridge Rd",
    zipcode: "77047",
  },
  cityId: 39051,
  timeOnZillow: "19 days",
  url: "/homedetails/12822-Southbridge-Rd-Houston-TX-77047/28138536_zpid/",
  zestimate: 178500,
  imgSrc:
    "https://photos.zillowstatic.com/fp/d69bf25daddc2be5690eaff36f579de6-p_d.jpg",
  description:
    "Welcome to your new home! This charming 3-bedroom, 1.5-bathroom residence offers a perfect blend of comfort and style in a coveted location. The formal living room provides a warm space for relaxation or entertaining guests, while the adjacent formal dining room is ideal for memorable dinners with family and friends. The well-appointed kitchen features modern amenities and a convenient pantry.    The master bedroom boasts an en-suite bathroom with a tub/shower combo and a walk-in closet. The home's carpeted rooms and ceiling fans throughout ensure a cozy and comfortable atmosphere. Step outside into the expansive backyard oasis, perfect for outdoor gatherings and recreation on the generous 5,665 sqft lot.    Additional features include a 1-car garage for added convenience. This property combines traditional charm with modern amenities, creating a place you'll be proud to call home.",
  price: 180000,
  livingAreaValue: 1215,
  resoFacts: {
    hasAttachedProperty: false,
    frontageType: null,
    poolFeatures: null,
    flooring: ["Carpet", "Laminate"],
    builderModel: null,
    accessibilityFeatures: null,
    hasGarage: true,
    hasPetsAllowed: null,
    bodyType: null,
    topography: null,
    landLeaseExpirationDate: null,
    hasAdditionalParcels: false,
    waterViewYN: null,
    livingQuarters: {},
    atAGlanceFacts: [
      {
        factValue: "Single Family Residence",
        factLabel: "Type",
      },
      {
        factValue: "1970",
        factLabel: "Year Built",
      },
      {
        factValue: "Natural Gas",
        factLabel: "Heating",
      },
      {
        factValue: "Electric, Ceiling Fan(s)",
        factLabel: "Cooling",
      },
      {
        factValue: "1 Attached Garage space",
        factLabel: "Parking",
      },
      {
        factValue: "5,667 sqft",
        factLabel: "Lot",
      },
      {
        factValue: "24 Days",
        factLabel: "Days on Zillow",
      },
      {
        factValue: "$148",
        factLabel: "Price/sqft",
      },
      {
        factValue: "3",
        factLabel: "Buyers Agency Fee",
      },
      {
        factValue: null,
        factLabel: "Offer Review Date",
      },
    ],
    offerReviewDate: null,
    horseYN: null,
    view: {},
    buyerAgencyCompensationType: "%",
    rooms: [
      {
        level: null,
        dimensions: null,
        features: null,
        roomAreaUnits: null,
        roomArea: null,
        roomAreaSource: null,
        roomType: "MasterBathroom",
        roomDescription: null,
        roomWidth: null,
        roomLevel: null,
        description: null,
        roomLengthWidthUnits: null,
        roomLength: null,
        roomFeatures: ["Half Bath"],
        roomDimensions: null,
        roomLengthWidthSource: null,
        area: null,
      },
      {
        level: null,
        dimensions: null,
        features: null,
        roomAreaUnits: null,
        roomArea: null,
        roomAreaSource: null,
        roomType: "Kitchen",
        roomDescription: null,
        roomWidth: null,
        roomLevel: null,
        description: null,
        roomLengthWidthUnits: null,
        roomLength: null,
        roomFeatures: ["Pantry"],
        roomDimensions: null,
        roomLengthWidthSource: null,
        area: null,
      },
    ],
    belowGradeFinishedArea: null,
    feesAndDues: {},
    cityRegion: "Houston",
    subAgencyCompensation: "3",
    hasPrivatePool: null,
    associationFeeIncludes: null,
    waterSource: ["Public"],
    carportParkingCapacity: 0,
    transactionBrokerCompensationType: null,
    hasFireplace: false,
    gas: null,
    sewer: ["Public Sewer"],
    elevationUnits: null,
    roadSurfaceType: null,
    mainLevelBedrooms: null,
    numberOfUnitsVacant: null,
    hasWaterfrontView: null,
    bathroomsOneQuarter: null,
    lotSize: "5,667 sqft",
    subAgencyCompensationType: "%",
    entryLevel: null,
    irrigationWaterRightsAcres: null,
    greenWaterConservation: null,
    stories: 1,
    bathrooms: 2,
    numberOfUnitsInCommunity: null,
    listingTerms:
      "Affordable Housing Program (subject to conditions),Cash,Conventional,FHA,VA Loan",
    otherParking: null,
    associationFee: null,
    marketingType: null,
    greenEnergyEfficient: ["Other Energy Features"],
    greenSustainability: null,
    heating: ["Natural Gas"],
    associationPhone: null,
    greenBuildingVerificationType: null,
    hasAttachedGarage: true,
    bedrooms: 3,
    architecturalStyle: "Traditional",
    listingId: null,
    structureType: "Free Standing",
    interiorFeatures: [
      "Formal Entry/Foyer",
      "All Bedrooms Down",
      "En-Suite Bath",
      "Walk-In Closet(s)",
      "Countertops(Laminate)",
    ],
    horseAmenities: null,
    electric: null,
    otherFacts: {},
    lotFeatures: ["Subdivided", "Back Yard", "0 Up To 1/4 Acre"],
    roofType: "Composition",
    compensationBasedOn: null,
    greenEnergyGeneration: null,
    taxAnnualAmount: 2880,
    daysOnZillow: 19,
    listAOR: null,
    hasHeating: true,
    elementarySchool: "Law Elementary School",
    constructionMaterials: ["Brick", "Wood Siding"],
    basementYN: null,
    hoaFeeTotal: null,
    appliances: ["Gas Oven", "Gas Range", "Disposal", "Microwave"],
    virtualTour: null,
    bathroomsPartial: null,
    fencing: null,
    yearBuiltEffective: null,
    foundationDetails: ["Slab"],
    buildingName: null,
    hasAssociation: null,
    isSeniorCommunity: null,
    propertySubType: ["Single Family Residence"],
    propertyCondition: null,
    hasCarport: false,
    canRaiseHorses: false,
    hasLandLease: false,
    communityFeatures: null,
    parcelNumber: "1013600000034",
    elevation: null,
    lotSizeDimensions: null,
    buildingAreaSource: null,
    contingency: null,
    yearBuilt: 1970,
    otherStructures: null,
    livingArea: "1,215 sqft",
    bathroomsFull: 1,
    livingAreaRangeUnits: null,
    incomeIncludes: null,
    highSchool: "Worthing High School",
    aboveGradeFinishedArea: null,
    isNewConstruction: false,
    inclusions: null,
    hasHomeWarranty: false,
    additionalFeeInfo: null,
    windowFeatures: null,
    ownership: "Full Ownership",
    woodedArea: null,
    middleOrJuniorSchoolDistrict: "27 - Houston",
    associationPhone2: null,
    exteriorFeatures: {},
    buildingFeatures: null,
    frontageLength: null,
    buildingArea: "1,215",
    associationAmenities: null,
    bathroomsHalf: 1,
    hasCooling: true,
    additionalParcelsDescription: null,
    parkingFeatures: ["Attached"],
    foundationArea: null,
    zoning: null,
    hoaFee: null,
    livingAreaRange: null,
    zoningDescription: null,
    developmentStatus: null,
    availabilityDate: null,
    waterfrontFeatures: null,
    waterBodyName: null,
    utilities: null,
    entryLocation: null,
    totalActualRent: null,
    hasView: false,
    subdivisionName: "South Acres Estates Sec 08",
    securityFeatures: ["Fire Alarm"],
    attic: null,
    fireplaceFeatures: null,
    mainLevelBathrooms: null,
    doorFeatures: null,
    ownershipType: null,
    associationName: null,
    associations: {},
    waterView: null,
    garageParkingCapacity: 1,
    cropsIncludedYN: null,
    laundryFeatures: ["Electric Dryer Hookup", "Washer Hookup"],
    buyerAgencyCompensation: "3",
    greenIndoorAirQuality: null,
    homeType: "SingleFamily",
    spaFeatures: null,
    municipality: null,
    bathroomsThreeQuarter: null,
    hasSpa: false,
    basement: null,
    associationFee2: null,
    cooling: ["Electric", "Ceiling Fan(s)"],
    openParkingCapacity: null,
    associationName2: null,
    hasRentControl: null,
    elementarySchoolDistrict: "27 - Houston",
    otherEquipment: null,
    commonWalls: null,
    specialListingConditions: null,
    furnished: false,
    vegetation: null,
    patioAndPorchFeatures: null,
    bathroomsFloat: 2,
    builderName: null,
    highSchoolDistrict: "27 - Houston",
    transactionBrokerCompensation: null,
    storiesTotal: null,
    cumulativeDaysOnMarket: null,
    fireplaces: 0,
    irrigationWaterRightsYN: null,
    exclusions: null,
    hasOpenParking: null,
    landLeaseAmount: null,
    coveredParkingCapacity: 1,
    middleOrJuniorSchool: "Thomas Middle School",
    hasElectricOnProperty: null,
    onMarketDate: 1715966610000,
    pricePerSquareFoot: 148,
    parkingCapacity: 1,
    levels: null,
  },

  taxHistory: [
    {
      time: 1686070004728,
      valueIncreaseRate: 0.15737899,
      taxIncreaseRate: -0.22737929,
      taxPaid: 919.72,
      value: 154958,
    },
    {
      time: 1654534004728,
      valueIncreaseRate: 0.17355177,
      taxIncreaseRate: 0,
      taxPaid: 1190.39,
      value: 133887,
    },
    {
      time: 1622998004728,
      valueIncreaseRate: 0.43446118,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 114087,
    },
    {
      time: 1591462004728,
      valueIncreaseRate: 0.16475551,
      taxIncreaseRate: 0.115329176,
      taxPaid: 1162.24,
      value: 79533,
    },
    {
      time: 1559839604728,
      valueIncreaseRate: 0,
      taxIncreaseRate: -0.37190863,
      taxPaid: 1042.06,
      value: 68283,
    },
    {
      time: 1528303604728,
      valueIncreaseRate: 0.03975819,
      taxIncreaseRate: 0,
      taxPaid: 1659.09,
      value: 68283,
    },
    {
      time: 1496767604728,
      valueIncreaseRate: 0.11936457,
      taxIncreaseRate: 0.118369505,
      taxPaid: 1659.09,
      value: 65672,
    },
    {
      time: 1465231604728,
      valueIncreaseRate: 0.24520333,
      taxIncreaseRate: 0.22482027,
      taxPaid: 1483.49,
      value: 58669,
    },
    {
      time: 1433609204728,
      valueIncreaseRate: 0,
      taxIncreaseRate: 0,
      taxPaid: 1211.19,
      value: 47116,
    },
    {
      time: 1402073204728,
      valueIncreaseRate: 0,
      taxIncreaseRate: 0,
      taxPaid: 1211.19,
      value: 47116,
    },
    {
      time: 1370537204728,
      valueIncreaseRate: 0,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 47116,
    },
    {
      time: 1339001204728,
      valueIncreaseRate: 0,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 47116,
    },
    {
      time: 1307378804728,
      valueIncreaseRate: -0.05768,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 47116,
    },
    {
      time: 1275842804728,
      valueIncreaseRate: -0.08645765,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 50000,
    },
    {
      time: 1244306804728,
      valueIncreaseRate: -0.083661206,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 54732,
    },
    {
      time: 1181148404728,
      valueIncreaseRate: 0.06658929,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 59729,
    },
    {
      time: 1149612404728,
      valueIncreaseRate: -0.047213953,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 56000,
    },
    {
      time: 1118076404728,
      valueIncreaseRate: 0.013362069,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 58775,
    },
    {
      time: 1086540404728,
      valueIncreaseRate: 0.062271062,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 58000,
    },
    {
      time: 1054918004728,
      valueIncreaseRate: 0.4,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 54600,
    },
    {
      time: 1023382004728,
      valueIncreaseRate: 0,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 39000,
    },
    {
      time: 991846004728,
      valueIncreaseRate: 0,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 39000,
    },
    {
      time: 960310004728,
      valueIncreaseRate: 0,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 39000,
    },
  ],

  brokerId: null,
  stateId: 54,
  streetAddress: "12822 Southbridge Rd",
  listingSubType: {
    is_FSBA: true,
    is_comingSoon: false,
    is_newHome: false,
    is_pending: true,
    is_forAuction: false,
    is_foreclosure: false,
    is_bankOwned: false,
    is_openHouse: false,
    is_FSBO: false,
  },
  solarPotential: null,
  dateSold: null,
  countyId: 1090,
  timeZone: "America/Chicago",
  homeType: "SINGLE_FAMILY",
  livingAreaUnits: "sqft",
  comingSoonOnMarketDate: null,
  rentZestimate: 1670,
  bathrooms: 2,
  annualHomeownersInsurance: 756,
  state: "TX",
  propertyTypeDimension: "Single Family",
  building: null,

  listed_by: {
    agent_reason: 3,
    zpro: false,
    recent_sales: 1,
    zuid: "X1-ZUydhl1y0gev49_2avjk",
    review_count: 870,
    display_name: "Alfonso Parodi",
    profile_url: "https://www.zillow.com/profile/tparodi/",
    business_name: "Realty Associates",
    rating_average: 5,
    phone: { prefix: "664", areacode: "832", number: "7967" },
    badge_type: "Listing Agent",
    image_url:
      "https://photos.zillowstatic.com/fp/224bf1d3cf24e137bb71959d483ef9d4-h_n.jpg",
  },
  yearBuilt: 1970,
  brokerageName: "Realty Associates",
  pageViewCount: 338,
  county: "Harris County",
  mortgageRates: { thirtyYearFixedRate: 6.275 },
  attributionInfo: {
    buyerAgentName: null,
    mlsName: "HAR",
    coAgentLicenseNumber: null,
    listingOffices: [[Object]],
    lastUpdated: "2024-06-04 05:28:50",
    buyerAgentMemberStateLicense: null,
    brokerName: "Realty Associates",
    listingAgreement: "Exclusive Right to Sell/Lease",
    infoString10:
      "Copyright 2024, Houston REALTORS® Information Service, Inc.\n" +
      "The information provided is exclusively for consumers’ personal, non-commercial use, and may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing. \n" +
      "Information is deemed reliable but not guaranteed.\n" +
      "\n" +
      "The listing broker’s offer of compensation is made only to participants of the MLS where the listing is filed. ",
    trueStatus: null,
    infoString3:
      "https://photos.zillowstatic.com/fp/c762e8317c35d5634ce97b86029da54d-zillow_web_95_35.jpg",
    agentEmail: null,
    agentName: "Alfonso Parodi",
    attributionTitle: null,
    mlsId: "4572352",
    coAgentName: null,
    coAgentNumber: null,
    infoString5: "713-530-2455",
    listingAgents: [[Object]],
    agentPhoneNumber: "713-530-2455",
    agentLicenseNumber: "TREC #0609745",
    providerLogo:
      "https://photos.zillowstatic.com/fp/c762e8317c35d5634ce97b86029da54d-zillow_web_95_35.jpg",
    infoString16: null,
    buyerBrokerageName: null,
    mlsDisclaimer:
      "Copyright 2024, Houston REALTORS® Information Service, Inc.\n" +
      "The information provided is exclusively for consumers’ personal, non-commercial use, and may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing. \n" +
      "Information is deemed reliable but not guaranteed.\n" +
      "\n" +
      "The listing broker’s offer of compensation is made only to participants of the MLS where the listing is filed. ",
    brokerPhoneNumber: "832-321-5072",
    lastChecked: "2024-06-06 09:21:07",
  },

  monthlyHoaFee: null,
  homeStatus: "PENDING",
  homeFacts: null,
  latitude: 29.623272,
  datePosted: "2024-05-17",
  bedrooms: 3,
  nearbyHomes: [
    {
      livingArea: 1338,
      livingAreaValue: 1338,
      lotAreaUnits: "Square Feet",
      lotAreaValue: 5662,
      lotSize: 5662,
      miniCardPhotos: [Array],
      zpid: 28138537,
      longitude: -95.36764,
      livingAreaUnits: "Square Feet",
      address: [Object],
      livingAreaUnitsShort: "sqft",
      price: 168500,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 29.623413,
    },
    {
      livingArea: 1238,
      livingAreaValue: 1238,
      lotAreaUnits: "Square Feet",
      lotAreaValue: 5662,
      lotSize: 5662,
      miniCardPhotos: [Array],
      zpid: 28138535,
      longitude: -95.36763,
      livingAreaUnits: "Square Feet",
      address: [Object],
      livingAreaUnitsShort: "sqft",
      price: 168800,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 29.623112,
    },
    {
      livingArea: 1234,
      livingAreaValue: 1234,
      lotAreaUnits: "Square Feet",
      lotAreaValue: 5662,
      lotSize: 5662,
      miniCardPhotos: [Array],
      zpid: 28138538,
      longitude: -95.36764,
      livingAreaUnits: "Square Feet",
      address: [Object],
      livingAreaUnitsShort: "sqft",
      price: 165700,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 29.623566,
    },
    {
      livingArea: 1188,
      livingAreaValue: 1188,
      lotAreaUnits: "Square Feet",
      lotAreaValue: 6751,
      lotSize: 6751,
      miniCardPhotos: [Array],
      zpid: 28138509,
      longitude: -95.36798,
      livingAreaUnits: "Square Feet",
      address: [Object],
      livingAreaUnitsShort: "sqft",
      price: 167600,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 29.62326,
    },
    {
      livingArea: 1244,
      livingAreaValue: 1244,
      lotAreaUnits: "Square Feet",
      lotAreaValue: 5662,
      lotSize: 5662,
      miniCardPhotos: [Array],
      zpid: 28138534,
      longitude: -95.36762,
      livingAreaUnits: "Square Feet",
      address: [Object],
      livingAreaUnitsShort: "sqft",
      price: 175900,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 29.62296,
    },
    {
      livingArea: 1271,
      livingAreaValue: 1271,
      lotAreaUnits: "Square Feet",
      lotAreaValue: 6751,
      lotSize: 6751,
      miniCardPhotos: [Array],
      zpid: 28138508,
      longitude: -95.36799,
      livingAreaUnits: "Square Feet",
      address: [Object],
      livingAreaUnitsShort: "sqft",
      price: 171200,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 29.62341,
    },
    {
      livingArea: 1646,
      livingAreaValue: 1646,
      lotAreaUnits: "Square Feet",
      lotAreaValue: 6751,
      lotSize: 6751,
      miniCardPhotos: [Array],
      zpid: 28138510,
      longitude: -95.36798,
      livingAreaUnits: "Square Feet",
      address: [Object],
      livingAreaUnitsShort: "sqft",
      price: 181800,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 29.62311,
    },
    {
      livingArea: 1163,
      livingAreaValue: 1163,
      lotAreaUnits: "Square Feet",
      lotAreaValue: 6751,
      lotSize: 6751,
      miniCardPhotos: [Array],
      zpid: 28138507,
      longitude: -95.36799,
      livingAreaUnits: "Square Feet",
      address: [Object],
      livingAreaUnitsShort: "sqft",
      price: 170800,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 29.623562,
    },
  ],
  livingArea: 1215,

  priceHistory: [
    {
      priceChangeRate: 0,
      date: "2024-05-24",
      source: "HAR",
      postingIsRental: false,
      time: 1716508800000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: [Object],
      pricePerSquareFoot: 148,
      buyerAgent: null,
      event: "Pending sale",
      price: 180000,
    },
    {
      priceChangeRate: 0,
      date: "2024-05-17",
      source: "HAR",
      postingIsRental: false,
      time: 1715904000000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: [Object],
      pricePerSquareFoot: null,
      buyerAgent: null,
      event: "Listing removed",
      price: null,
    },
    {
      priceChangeRate: 0.028571428571429,
      date: "2024-04-12",
      source: "HAR",
      postingIsRental: false,
      time: 1712880000000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: [Object],
      pricePerSquareFoot: 148,
      buyerAgent: null,
      event: "Price change",
      price: 180000,
    },
    {
      priceChangeRate: 0,
      date: "2024-04-04",
      source: "HAR",
      postingIsRental: false,
      time: 1712188800000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: [Object],
      pricePerSquareFoot: 144,
      buyerAgent: null,
      event: "Pending sale",
      price: 175000,
    },
    {
      priceChangeRate: -0.078947368421053,
      date: "2024-03-22",
      source: "HAR",
      postingIsRental: false,
      time: 1711065600000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: [Object],
      pricePerSquareFoot: 144,
      buyerAgent: null,
      event: "Price change",
      price: 175000,
    },
    {
      priceChangeRate: -0.11627906976744,
      date: "2024-02-21",
      source: "HAR",
      postingIsRental: false,
      time: 1708473600000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: [Object],
      pricePerSquareFoot: 156,
      buyerAgent: null,
      event: "Price change",
      price: 190000,
    },
    {
      priceChangeRate: 0,
      date: "2024-01-09",
      source: "HAR",
      postingIsRental: false,
      time: 1704758400000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: [Object],
      pricePerSquareFoot: 177,
      buyerAgent: null,
      event: "Listed for sale",
      price: 215000,
    },
    {
      priceChangeRate: 0,
      date: "2015-01-26",
      source: "Public Record",
      postingIsRental: false,
      time: 1422230400000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: [Object],
      pricePerSquareFoot: null,
      buyerAgent: null,
      event: "Sold",
      price: null,
    },
  ],
  favoriteCount: 33,
  schools: [
    {
      link: "https://www.greatschools.org/texas/houston/3452-Law-Elementary-School/",
      rating: 5,
      totalCount: null,
      distance: 0.4,
      assigned: null,
      name: "Law Elementary School",
      studentsPerTeacher: null,
      isAssigned: null,
      size: null,
      level: "Primary",
      grades: "PK-5",
      type: "Public",
    },
    {
      link: "https://www.greatschools.org/texas/houston/3530-Thomas-Middle-School/",
      rating: 4,
      totalCount: null,
      distance: 2.4,
      assigned: null,
      name: "Thomas Middle School",
      studentsPerTeacher: null,
      isAssigned: null,
      size: null,
      level: "Middle",
      grades: "6-8",
      type: "Public",
    },
    {
      link: "https://www.greatschools.org/texas/houston/3550-Worthing-High-School/",
      rating: 2,
      totalCount: null,
      distance: 2.4,
      assigned: null,
      name: "Worthing High School",
      studentsPerTeacher: null,
      isAssigned: null,
      size: null,
      level: "High",
      grades: "9-12",
      type: "Public",
    },
  ],
  zestimateHighPercent: "5",
  mlsid: "4572352",
  countyFIPS: "48201",
  city: "Houston",
  providerListingID: null,
  country: "USA",
  currency: "USD",
  isListedByOwner: null,
  contingentListingType: null,
};

//console.log(propertyDataFromAPI);
