import { AgentDataTypes } from "./realtorTypes";

export const agentData: AgentDataTypes = {
  about: {
    yearsExperience: "2021",
    title: null,
    description:
      "<p>I have been under the umbrella of the real estate industry for 3 Years. Starting off as a Notary-Signing Agent for mortgage &amp; real estate transactions exposed me to the multiple documents pertinent to the industry; thouroughly understanding each individual document in a Single Family Residense transaction. From their I pivoted to becoming a Mortgage Loan Officer, being dualy licensed in the state of Texas and Florida. This career path introduced me to the mortgage industries protocols, its dynamics and diversities and the many loan product options available.&#160;</p>\n" +
      "<p></p>\n" +
      "<p>My ultimate destination has been Real Estate Industry; here, at your service. The journey has been plentiful with experiences which serve as a point of reference for YOU and your FAMILY. Together with the Parodi Group your journey is destined smoothly.</p>\n",
    specialties: [
      "Buyer's agent",
      "Listing agent",
      "Consulting/advice",
      "Notary",
    ],
  },
  forSaleListings: { listings: {}, listing_count: 0 },
  pastSales: {
    past_sales: [
      {
        bathrooms: 2,
        state: "TX",
        longitude: -95.59015,
        latitude: 29.669825,
        bedrooms: 3,
        represented: "Both",
        street_address: "12019 Fairpoint Dr",
        city_state_zipcode: "Houston, TX, 77099",
        image_alt: "12019 Fairpoint Dr, Houston, TX, 77099",
        sold_date: "5/31/2024",
        zpid: 28391003,
        livingAreaUnitsShort: "sqft",
        livingAreaValue: 1693,
        city: "Houston",
        medium_image_url:
          "https://maps.googleapis.com/maps/api/streetview?location=12019+Fairpoint+Dr%2C+Houston%2C+TX+77099&size=400x300&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=epHzj9VLv4voOL9vrzCqrf-7YBk=",
        home_details_url:
          "/homedetails/12019-Fairpoint-Dr-Houston-TX-77099/28391003_zpid/",
        image_url:
          "https://maps.googleapis.com/maps/api/streetview?location=12019+Fairpoint+Dr%2C+Houston%2C+TX+77099&size=101x76&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=KHOGCSUUeEwfu_7yKCHZmOvy68w=",
        mlsLogoSrc: null,
        price: "--",
      },
      {
        bathrooms: 2,
        state: "TX",
        longitude: -95.19061,
        latitude: 29.784649,
        bedrooms: 4,
        represented: "Buyer",
        street_address: "13311 Indianapolis St",
        city_state_zipcode: "Houston, TX, 77015",
        image_alt: "13311 Indianapolis St, Houston, TX, 77015",
        sold_date: "5/19/2024",
        zpid: 27927869,
        livingAreaUnitsShort: "sqft",
        livingAreaValue: 1587,
        city: "Houston",
        medium_image_url:
          "https://photos.zillowstatic.com/fp/9ec7d9340d3badcfa30ccd6a95ab5124-p_d.jpg",
        home_details_url:
          "/homedetails/13311-Indianapolis-St-Houston-TX-77015/27927869_zpid/",
        image_url:
          "https://photos.zillowstatic.com/fp/9ec7d9340d3badcfa30ccd6a95ab5124-p_b.jpg",
        mlsLogoSrc: null,
        price: "--",
      },
      {
        bathrooms: 2,
        state: "TX",
        longitude: -95.41846,
        latitude: 29.891459,
        bedrooms: 3,
        represented: "Buyer",
        street_address: "1010 Peach Spring Dr",
        city_state_zipcode: "Houston, TX, 77088",
        image_alt: "1010 Peach Spring Dr, Houston, TX, 77088",
        sold_date: "5/8/2024",
        zpid: 28151548,
        livingAreaUnitsShort: "sqft",
        livingAreaValue: 1608,
        city: "Houston",
        medium_image_url:
          "https://maps.googleapis.com/maps/api/streetview?location=1010+Peach+Spring+Dr%2C+Houston%2C+TX+77088&size=400x300&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=BGmwlFfhCXcb7WgWwHsgYpiH5mg=",
        home_details_url:
          "/homedetails/1010-Peach-Spring-Dr-Houston-TX-77088/28151548_zpid/",
        image_url:
          "https://maps.googleapis.com/maps/api/streetview?location=1010+Peach+Spring+Dr%2C+Houston%2C+TX+77088&size=101x76&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=lvfWUwv3fj7xl0dEMioX7i6TP2I=",
        mlsLogoSrc: null,
        price: "--",
      },
      {
        bathrooms: 3,
        state: "TX",
        longitude: -95.67578,
        latitude: 30.11906,
        bedrooms: 4,
        represented: "Buyer",
        street_address: "26119 Brahman Dr",
        city_state_zipcode: "Magnolia, TX, 77355",
        image_alt: "26119 Brahman Dr, Magnolia, TX, 77355",
        sold_date: "3/25/2024",
        zpid: 2055805663,
        livingAreaUnitsShort: "sqft",
        livingAreaValue: 2284,
        city: "Magnolia",
        medium_image_url:
          "https://photos.zillowstatic.com/fp/f700b583d9175b11e832626e2822df40-p_d.jpg",
        home_details_url:
          "/homedetails/26119-Brahman-Dr-Magnolia-TX-77355/2055805663_zpid/",
        image_url:
          "https://photos.zillowstatic.com/fp/f700b583d9175b11e832626e2822df40-p_b.jpg",
        mlsLogoSrc:
          "https://photos.zillowstatic.com/fp/199360cc2ba8208f757aefe421ca9024-zillow_web_95_35.jpg",
        price: "--",
      },
      {
        bathrooms: 2,
        state: "TX",
        longitude: -95.22107,
        latitude: 29.653067,
        bedrooms: 4,
        represented: "Buyer",
        street_address: "808 Avenue N",
        city_state_zipcode: "South Houston, TX, 77587",
        image_alt: "808 Avenue N, South Houston, TX, 77587",
        sold_date: "3/21/2024",
        zpid: 27781228,
        livingAreaUnitsShort: "sqft",
        livingAreaValue: 1996,
        city: "South Houston",
        medium_image_url:
          "https://maps.googleapis.com/maps/api/streetview?location=808+Avenue+N%2C+South+Houston%2C+TX+77587&size=400x300&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=3wn40h3uPkHWA93hyFIZ09sOK7M=",
        home_details_url:
          "/homedetails/808-Avenue-N-South-Houston-TX-77587/27781228_zpid/",
        image_url:
          "https://maps.googleapis.com/maps/api/streetview?location=808+Avenue+N%2C+South+Houston%2C+TX+77587&size=101x76&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=EqC_0xL8k2zzKU5f11VlqWwo_FI=",
        mlsLogoSrc: null,
        price: "--",
      },
    ],
    total: 12,
  },
  serviceAreas: [
    { url: "/spring-tx", regionId: 7204, text: "Spring, TX" },
    { url: "/pearland-tx", regionId: 13234, text: "Pearland, TX" },
    { url: "/katy-tx", regionId: 18800, text: "Katy, TX" },
    { url: "/houston-tx", regionId: 39051, text: "Houston, TX" },
    { url: "/humble-tx", regionId: 39071, text: "Humble, TX" },
    { url: "/sugar-land-tx", regionId: 41114, text: "Sugar Land, TX" },
    {
      url: "/missouri-city-tx",
      regionId: 53360,
      text: "Missouri City, TX",
    },
  ],
  profileDisplay: {
    actionToolbar: {
      isMenu: false,
      isToolbar: true,
      share: null,
      editProfileInformation: null,
      deviceType: "mobile",
      switchToPublic: null,
      hide: false,
      switchToPrivate: null,
      publicActionBar: [Object],
      requestReviews: null,
    },
    teamMembers: {
      message: "Agent is not a team lead or does not have team members.",
      hide: true,
      errorCode: "DoNotDisplay",
    },
    hide: false,
    contactCard: {
      reviewsPath: "/profile/leonoboa/#reviews",
      profilePhotoSrc:
        "https://photos.zillowstatic.com/h_l/IS3b9th2jc1gf11000000000.jpg",
      actionBar: [Object],
      isTeamLead: false,
      teamProfilePath: null,
      profilePhotoIsvalid: true,
      isTeamMember: false,
      profilePhotoHeight: 240,
      firstName: "Leo",
      teamRank: null,
      profilePath: "/profile/leonoboa/",
      name: "Leo Noboa",
      contactCardType: "agent",
      profilePhotoWidth: 240,
      hide: false,
      flag: [Object],
      editProfilePhoto: null,
      agentTypeDisplay: [Object],
      teamName: null,
      allActivity: [Object],
      profilePhotoAlt: "Leo Noboa's Profile Photo",
    },
    teamSummary: {
      message: "Agent is not a team member.",
      hide: true,
      errorCode: "DoNotDisplay",
    },
    private: false,
    profileInfo: {
      isEmployee: false,
      isPremierAgent: false,
      screenName: "leonoboa",
      isTeamLead: false,
      isTeamAccount: false,
      isLender: false,
      encodedZuid: "X1-ZUrk0z0wdwyia1_5f91c",
      hide: false,
      isZillowGroupEmployee: false,
      isTeamMember: false,
      teamName: null,
      isProfessional: true,
      userRating: 5,
    },
    actionMenu: {
      message:
        "Do not show the profile action menu on public profiles of other people.",
      hide: true,
      errorCode: "DoNotDisplay",
    },
  },

  reviewsParams: null,
  displayUser: {
    profileTypeIds: [1, 2],
    cpdUserPronouns: "He/Him/His",
    isTopAgent: false,
    ratings: { count: 7, average: 5 },
    screenName: "leonoboa",
    inCanada: false,
    sidebarVideoUrl: null,
    isPremierAgent: false,
    profilePhotoSrc:
      "https://photos.zillowstatic.com/fp/dc5fcad729b5541ad834c5c66c6c3dd9-h_l.jpg",
    businessName: "GregTXRealty",
    businessAddress: { city: "Houston", state: "TX" },
    flag: 229263221,
    encodedZuid: "X1-ZUrk0z0wdwyia1_5f91c",
    name: "Leo Noboa",
    profileTypes: ["consumer", "agent"],
  },

  lastYearPastSalesTotal: { count: 11 },
  reviewsData: {
    reviews: [[Object], [Object], [Object], [Object], [Object]],
    filters: [[Object], [Object]],
  },
  professionalInformation: [
    { term: "Broker address", lines: [Array] },
    { term: "Cell phone", description: "(423) 615-4240" },
    { term: "Screenname", description: "leonoboa" },
    { term: "Member since", description: "04/24/2023" },
    { term: "Real Estate Licenses", lines: [Array] },
    { term: "Languages", description: "English, Spanish, Portuguese" },
  ],
  preferredLenders: { lenders: {} },
  forRentListings: { listings: {}, listing_count: 0 },
  map: {
    mapApiKey: "AIzaSyD4w61UyrLSs5ozaHmCCrhvnyPrJdNkZQ0",
    mapCentroid: { longitude: "-95.392486", latitude: "29.806593" },
  },
};
